---
- name: Install Postgres-Package
  apt:
    name: [ "postgresql", "python3-psycopg2" ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes

- name: adding existing admin-users to group postgres
  user:
    name: '{{ item.name }}'
    groups: postgres
    append: yes
  become: yes
  with_items: 
    - "{{ admin_users }}"