---
- name: Install PostgreSQL Database Server Software
  include_tasks: install.yml
  when: 
    - postgres is defined

- name: Check if postgres is running
  ansible.builtin.systemd:
    name: postgresql
    daemon_reload: yes
    state: started
    enabled: yes
  become: yes
  when: 
    - postgres is defined

- name: Check Data Directory of PostgreSQL Database Server
  community.general.postgresql_query:
    db: postgres
    query: SHOW data_directory;
  become: yes
  become_user: "postgres"
  changed_when: false
  when: 
    - postgres is defined
  ignore_errors: yes
  register: datadir_location

# - name: Info to Data Directory of PostgreSQL Database Server
#   ansible.builtin.debug:
#     msg: "{{ datadir_location.failed }}"

- name: Move PostgreSQL Database Data-Directory
  include_tasks: move_datadir.yml
  when: 
    - postgres is defined
    - postgres.datadir is defined
    - not datadir_location.failed
    - postgres.datadir not in datadir_location.query_result[0]['data_directory']

- name: Configure PostgreSQL Database Server
  include_tasks: configure.yml
  when: 
    - postgres is defined