---
- name: restart postgres
  ansible.builtin.systemd:
    name: postgresql
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: yes
  ignore_errors: yes

- name: reload postgres
  ansible.builtin.systemd:
    name: postgresql
    daemon_reload: yes
    state: reloaded
    enabled: yes
  become: yes
  ignore_errors: yes